services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest_realtime_app
      MYSQL_USER: devteam
      MYSQL_PASSWORD: soksan
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    environment:
      - REDIS_PASSWORD=soksan

volumes:
  mysql-data:
  redis-data:
